<?php
session_start();
$Msg="";
require_once('Database.php');
if(isset($_SESSION['role'])){
	include('head.php');
?>
	<body>
		<div id="app">
<?php
//perform access management
if($_SESSION['role']=="Administrator"){
	include('include/sidebar.php');
}else if($_SESSION['role']=="teacher"){
	include('include/tsidebar.php');
}else if($_SESSION['role']=="Accountant"){
	include('include/asidebar.php');
}else{
	echo "";
}
if(isset($_POST['sub'])){
	$names=strip_tags($_POST['names']);
	$init=$_POST['init'];
	$email=strip_tags($_POST['email']);
	$gender=$_POST['gender'];
	$dob=$_POST['dob'];
	$empNumber=$_POST['empNumber'];
	$designation=$_POST['designation'];
	$department=$_POST['department'];
	$teachingSubject1=$_POST['teachingSubject1'];
	$teachingSubject2=$_POST['teachingSubject2'];
	$academicLevel=$_POST['academicLevel'];
	$salary=$_POST['pay'];
	$health=$_POST['health'];
	$tel=$_POST['tel'];
	$password=$_POST['password'];
	$empTerm=$_POST['empTerm'];
	$nationality=$_POST['nationality'];
	$previousEmployer=$_POST['previousEmployer'];
	$kra=$_POST['kra'];
	$idNumber=$_POST['idNumber'];
	//passport image upload
	// $file=$_FILES['logo']['name'];
	// $tmpName=$_FILES['logo']['tmp_name'];
	// move_uploaded_file($tmpName, "teachers/$file");
	$db=new Database();
	$db->createUser($names,sha1($password),'teacher');
	$db->query("INSERT INTO teacher(names,Initial,email,gender,bdate,empNumber,designation,department,major,minor,
	academicLevel,salary,health,phone,password,empType,nationality,previousEmployer,kraPin,idNumber,passportName,empDate,role) VALUES(:names,:init,:email,:gender,:bdate,:empNumber,:designation,:department,:major,:minor,
	:academicLevel,:salary,:health,:phone,:password,:empType,:nationality,:previousEmployer,:kraPin,:idNumber,:passportName,:empDate,:role)");
	$db->bind(':names',$names);
	$db->bind(':init',$init);
	$db->bind(':email',$email);
	$db->bind(':gender',$gender);
	$db->bind(':bdate',$dob);
	$db->bind(':empNumber',$empNumber);
	$db->bind(':designation',$designation);
	$db->bind(':department',$department);
	$db->bind(':major',$teachingSubject1);
	$db->bind(':minor',$teachingSubject2);
	$db->bind(':academicLevel',$academicLevel);
	$db->bind(':salary',$salary);
	$db->bind(':health',$health);
	$db->bind(':phone',$tel);
	$db->bind(':password',sha1($password));
	$db->bind(':empType',$empTerm);
	$db->bind(':nationality',$nationality);
	$db->bind(':previousEmployer',$previousEmployer);
	$db->bind(':kraPin',$kra);
	$db->bind(':idNumber',$idNumber);
	$db->bind(':passportName','default.png');
	$db->bind(':empDate',date("y-M-d"));
	$db->bind(':role','teacher');
	if($db->execute()){
		$Msg="<div class='alert alert-success'id='alert'>
			<strong>Success!!! Teacher Added</strong>
		</div>";
	}else{
		$Msg="<div class='alert alert-danger'id='alert'>
			<strong>Teacher Added</strong>
		</div>";
	}
}

?>
			<div class="app-content">

						<?php include('include/header.php');?>

				<!-- end: TOP NAVBAR -->
				<div class="main-content" >
					<span style="font-size:20px"><span class="text-primary">Add a New Teacher</span></span>
					<div class="container">
					<form method="POST" action="addTeacher.php" enctype="multipart/form-data">
						<?php echo $Msg;?>
						<div class="row">
							<div class="col-sm-3">
								<label for="names" class="control-label">Enter the names</label>&nbsp;<i class="fa fa-tags"style="color:red"></i>
								<input type="text" class="form-control" name="names" placeholder="Enter the names here" required maxlength="30"/>
							</div>
							<div class="col-sm-3">
								<label for="names" class="control-label">Enter the Initials</label>&nbsp;<i class="fa fa-tag"style="color:red"></i>
								<input type="text" class="form-control" name="init" placeholder="Enter the Initials Here" required maxlength="30"/>
							</div>
							<div class="col-sm-3">
								<label for="email" class="label-control">Email</label>&nbsp;<i class="fa fa-envelope"style="color:red"></i>
								<input type="email" class="form-control" name="email" placeholder="Enter the Email" required/>
							</div>
							<div class="col-sm-3">
								<label for="gender" class="label-control">Gender</label>&nbsp;<i class="fa fa-users"style="color:red"></i>
								<select name="gender" class="form-control">
									<option>--SELECT GENDER--</option>
									<option>Male</option>
									<option>Female</option>
								</select>
							</div>
							<div class="col-sm-3">
								<label for="Birthdate" class="label-control">Birth Date</label>&nbsp;<i class="fas fa-baby"style="color:red"></i>
								<input type="date" class="form-control" name="dob"/>
							</div>
							<div class="col-sm-3">
								<label for="Employee Number" class="label-control">Employee Number/TSC Number</label>&nbsp;<i class="fas fa-tags"style="color:red"></i>
								<!--[generated by the system]-->
								<input type="text" class="form-control" name="empNumber" placeholder="Employee Number"/>
							</div>
							<div class="col-sm-3">
								<label for="Designation" class="label-control">Designation</label>&nbsp;<i class="fa fa-list"style="color:red"></i>
								<!--[to be fetched form the database]-->
								<select name="designation" class="form-control">
									<option>--SELECT DESIGNATION--</option>
									<?php $database=new Database();
									$results=$database->displayApproved('designation');
									foreach ($results as $key) {
									?>
									<option><?php echo $key->designation;?></option>
								<?php }?>
								</select>
							</div>
							<div class="col-sm-3">
								<label for="Department" class="label-control">Department</label>&nbsp;<i class="fa fa-bank"style="color:red"></i>
								<select name="department" class="form-control">
									<option>--SELECT DEPARTMENTS--</option>
									<?php $database=new Database();
									$results=$database->displayApproved('department');
									foreach ($results as $key) {
									?>
									<option><?php echo $key->department;?></option>
								<?php }?>
								</select>
							</div>
							<div class="col-sm-3">
								<label for="Subject" class="label-control">Teaching Subject 1</label>&nbsp;<i class="fa fa-book" style="color:red"></i>
								<select name="teachingSubject1" class="form-control">
									<option>--SELECT SUBJECT 1--</option>
									<?php $database=new Database();
									$results=$database->displayApproved('subject');
									foreach ($results as $key) {
									?>
									<option><?php echo $key->subjectName;?></option>
								<?php }?>
								</select>
							</div>
							<div class="col-sm-3">
								<label for="subject" class="label-control">Teaching Subject 2</label>&nbsp;<i class="fa fa-book" style="color:red"></i>
								<select name="teachingSubject2" class="form-control">
									<option>--SELECT SUBJECT 2--</option>
									<?php $database=new Database();
									$results=$database->displayApproved('subject');
									foreach ($results as $key) {
									?>
									<option><?php echo $key->subjectName;?></option>
								<?php }?>
								</select>
							</div>
							<div class="col-sm-3">
								<label for="level" class="label-control">Academic Level</label>&nbsp;<i class="fa fa-graduation-cap" style="color:red"></i>
								<input type="text" class="form-control" name="academicLevel" placeholder="eg. Bachelors,Masters..." />
							</div>
							<div class="col-sm-3">
								<label for="pay" class="label-control">Salary</label>&nbsp;<i class="fas fa-hand-holding-usd" style="color:red"></i>
								<input type="number" class="form-control" name="pay" placeholder="Amount paid by the employer" />
							</div>
							<div class="col-sm-3">
								<label for="" class="label-control">Disabled</label>&nbsp;<i class="fas fa-ribbon" style="color:red"></i>
								<select name="health" class="form-control">
									<option>--SELECT OPTION--</option>
									<option>Yes</option>
									<option>No</option>
								</select>
							</div>
							<div class="col-sm-3">
								<label for="subject" class="label-control">Telephone</label>&nbsp;<i class="fa fa-phone" style="color:red"></i>
									<input type="number" class="form-control" name="tel" placeholder="eg.+254796844938" />
							</div>
							<div class="col-sm-3">
								<label for="level" class="label-control">Password</label>&nbsp;<i class="fa fa-lock" style="color:red"></i>
								<?php
								$str='abshkoeuh)(!@^&*$_+pl7';
								$empPassword=substr(str_shuffle($str), 8,16);
								?>
								<input type="text" class="form-control" name="password" value="<?php echo $empPassword;?>" />
							</div>
							<div class="col-sm-3">
								<label for="pay" class="label-control">Terms of Employment</label>&nbsp;<i class="fas fa-question" style="color:red"></i>
								<select name="empTerm" class="form-control">
									<option>--SELECT TYPE--</option>
									<option>Permanent</option>
									<option>Contractual</option>
									<option>Temporary</option>
								</select>
							</div>
							<div class="col-sm-3">
								<label for="" class="label-control">Nationality</label>&nbsp;<i class="fas fa-star" style="color:red"></i>
									<input type="text" class="form-control" name="nationality" placeholder="eg. Kenyan" />
							</div>
							<div class="col-sm-3">
								<label for="" class="label-control">Previous Employer</label>&nbsp;<i class="fas fa-user" style="color:red"></i>
								<input type="text" class="form-control" name="previousEmployer" placeholder="Leave empty if None" />
							</div>
							<div class="col-sm-3">
								<label for="subject" class="label-control">KRA PIN NUMBER</label>&nbsp;<i class="fa fa-file" style="color:red"></i>
									<input type="text" class="form-control" name="kra" placeholder="eg. A990089746R" />
							</div>
							<div class="col-sm-3">
								<label for="level" class="label-control">ID NUMBER</label>&nbsp;<i class="fas fa-id-card" style="color:red"></i>
								<input type="number" class="form-control" name="idNumber" placeholder="eg.33432289" />
							</div>
							<!-- <div class="col-sm-3">
								<label for="" class="label-control">Passport Photo</label>&nbsp;<i class="fas fa-image" style="color:red"></i>
								<input type="file" name="logo" />
							</div> -->
						</div>
						<button class="badge badge-primary" name="sub" type="submit" style="margin-top:20px">Add Teacher</button>
					</form>
				</div>
				</div>
			</div>
			<!-- start: FOOTER -->
	<?php include('include/footer.php');?>
		</div>
		<!-- start: MAIN JAVASCRIPTS -->
		<script src="vendor/jquery/jquery.min.js"></script>
		<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
		<script src="vendor/modernizr/modernizr.js"></script>
		<script src="vendor/jquery-cookie/jquery.cookie.js"></script>
		<script src="vendor/perfect-scrollbar/perfect-scrollbar.min.js"></script>
		<script src="vendor/switchery/switchery.min.js"></script>
		<script src="assets/js/main.js"></script>

		<script>
			jQuery(document).ready(function() {
				Main.init();
				FormElements.init();
			});
		</script>
		<!-- end: JavaScript Event Handlers for this page -->
		<!-- end: CLIP-TWO JAVASCRIPTS -->
	</body>
</html>
<?php }else{
	header("location: index.php");
}
