<?php
session_start();
if(isset($_SESSION['role'])){
  $_SESSION['class']=$_GET['Class'];
  $_SESSION['term']=$_GET['Term'];
  $_SESSION['year']=$_GET['Year'];
  $_SESSION['exam']=$_GET['Exam'];
  $_SESSION['stream']=$_GET['Stream'];
  require_once('Database.php');
  $db=new Database();
	include('include/fpdf.php');
	class myClass extends FPDF{
    public $angle;
    public function Header(){
      $database=new Database();
      $details=$database->getSchool();
      foreach ($details as $key) {
        $this->SetFont('Arial','B','90');
        if($database->checkWatermark()){
          $this->watermark($key->sName,26,11);
        }else{
          continue;
        }
        $this->SetFont('Arial','B','10');
      }

    }
    function watermark($text,$angle,$start){
      $this->SetTextColor(255,200,233);
      $this->Rotate($angle,20,200);
      $this->Text($start,190,$text);
      $this->Rotate(0);
    }
    function Rotate($angle,$x=-1,$y=-1)
    {
      if($x==-1)
        $x=$this->x;
      if($y==-1)
        $y=$this->y;
      if($this->angle!=0)
        $this->_out('Q');
      $this->angle=$angle;
      if($angle!=0)
      {
        $angle*=M_PI/180;
        $c=cos($angle);
        $s=sin($angle);
        $cx=$x*$this->k;
        $cy=($this->h-$y)*$this->k;
        $this->_out(sprintf('q %.2F %.2F %.2F %.2F %.2F %.2F cm 1 0 0 1 %.2F %.2F cm',$c,$s,-$s,$c,$cx,$cy,-$cx,-$cy));
      }
    }
    function _endpage()
    {
      if($this->angle!=0)
      {
        $this->angle=0;
        $this->_out('Q');
      }
      parent::_endpage();
    }
		function head($db,$class,$stream){
			$this->SetFont('Arial','',12);
      //$this->SetFont('Arial','',10);
      $detail=$db->getSchool();
      foreach($detail as $key){
				$this->Image('assets/images/'.$key->Image,40,10,0,25);
				$this->SetFont('Courier','B','30');
				$this->Cell(440,20,$key->sName,0,0,'C');
        $this->Ln(15);
        $this->SetFont('Courier','B','15');
				$this->Cell(440,5,"Tel :".$key->Phone,0,0,'C');
        $this->Ln();
        $this->SetFont('Courier','B','15');
				$this->Cell(440,5,"P.O.Box ".$key->pBox." ".$key->pCode." ".$key->pCity." Kenya",0,0,'C');
				$this->Ln(8);
        $this->SetFont('Arial','B','15');
				$this->Cell(440,5,"Form ".$class." Students",0,0,'C');
				$this->Ln(8);
        $this->Cell(440,5,$_SESSION['exam']." Exam Correction Sheet",0,0,'C');
        $this->Ln(10);
      }
		}
		function footer(){
			$this->SetY(-15);
			$this->SetFont('Arial','','10');
      $this->Cell(0,10,'=======================================================================================',0,0);
      $this->Ln(3);
			$this->Cell(0,10,'The School holds the right to edit the contents of this Document when necessary',0,0);
			$this->SetX(-40);
      $this->Ln();
      $this->SetTextColor(125,125,125);
			$this->Cell(0,0,'Generated By '.$_SESSION['role'],0,0);
		}
		function headerTable(){
			$this->SetFont('courier','',12);
			$this->Cell(22,5,'S/N',1,0,'C');
			$this->Cell(15,5,'Reg',1,0,'C');
			$this->Cell(90,5,'Names',1,0,'C');
      $database=new Database();
      $database->query("SELECT * FROM subject WHERE status=:status");
      $database->bind(':status',1);
      $subject=$database->resultSet();
      foreach ($subject as $key) {
       $this->Cell(25,5,$key->subjectAbbr,1,0,'C');
      }
			$this->Ln();
		}
		function viewTable($db){
			$this->SetFont('Arial','',8);
      $db->query("SELECT * FROM examTotals WHERE Class=:class AND Stream=:stream ORDER BY studentReg ASC");
      $db->bind(':class',$_SESSION['class']);
      $db->bind(':stream',$_SESSION['stream']);
      $results=$db->resultSet();
      $total=0;
      $count=1;
      $ct=1;
      foreach ($results as $data) {
        $this->SetFont('courier','I',12);
				$this->Cell(22,5,$ct,1,0,'C');
        $ct=$ct+1;
				$this->Cell(15,5,$data->studentReg,1,0,'C');
        $this->SetFont('courier','I',12);
        $db=new Database();
				$this->Cell(90,5,$db->getName($data->studentReg),1,0,'L');
        $this->SetFont('courier','I',12);
        $db->query("SELECT * FROM subject WHERE status=:status");
        $db->bind(':status',1);
        $subject=$db->resultSet();
        $marks=0;
        $count=0;
        $cnt=1;
        foreach ($subject as $key) {
        $mark=$db->getMarks($key->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['year'],$data->studentReg);
        if($mark=="--"){
          $this->Cell(25,5,$mark,1,0,'L');
        }else{
          if($mark<10 && $mark>0){
            $this->Cell(25,5,"0".$mark,1,0,'L');
          }else{
            $this->Cell(25,5,$mark,1,0,'L');
          }
          $count=$count+1;
          $cnt=$cnt+1;
        }
        }
        $mean=round($data->total/$cnt-1);
        // $abs=$mean/100;
        // $grade=round($abs*12);
        $this->Ln();
        $total=$total+1;
			}
      	//$this->Ln(10);
      $this->SetTextColor(0,0,0);
      $this->Cell(250,10,"Total ",0,0,'C');
      $this->Cell(10,10,"===========",0,0,'C');
      $this->Ln();
      $this->Cell(250,10,"",0,0,'C');
      if($total==0){
        $this->Cell(10,10,"No students Records Found",0,0,'C');
      }
      else{
        $this->Cell(10,10,$total." Students",0,0,'C');
      }
      $this->Ln(3);
      $this->Cell(250,10," ",0,0,'C');
      $this->Cell(10,10,"===========",0,0,'C');
		}
	}
	$pdf=new myClass();
	$pdf->AliasNbPages();
	  $pdf->AddPage('L','A3',0);
	$pdf->head($db,$_SESSION['class'],$_SESSION['stream']);
	$pdf->headerTable();
	$pdf->viewTable($db);
	$pdf->output();
}else{  header("Location: index.php");}
?>
