<?php
session_start();
if(isset($_SESSION['role'])){
  require_once('Database.php');
  $db=new Database();
	include('include/fpdf.php');
	class myClass extends FPDF{
    public $angle;
    public function Header(){
      $database=new Database();
      $details=$database->getSchool();
      foreach ($details as $key) {
        $this->SetFont('Arial','B','50');
        if($database->checkWatermark()){
          $this->watermark($key->sName,30,11);
        }else{
          continue;
        }
        $this->SetFont('Arial','B','10');
      }

    }
    function watermark($text,$angle,$start){
      $this->SetTextColor(255,200,233);
      $this->Rotate($angle,20,200);
      $this->Text($start,190,$text);
      $this->Rotate(0);
    }
    function Rotate($angle,$x=-1,$y=-1)
    {
      if($x==-1)
        $x=$this->x;
      if($y==-1)
        $y=$this->y;
      if($this->angle!=0)
        $this->_out('Q');
      $this->angle=$angle;
      if($angle!=0)
      {
        $angle*=M_PI/180;
        $c=cos($angle);
        $s=sin($angle);
        $cx=$x*$this->k;
        $cy=($this->h-$y)*$this->k;
        $this->_out(sprintf('q %.2F %.2F %.2F %.2F %.2F %.2F cm 1 0 0 1 %.2F %.2F cm',$c,$s,-$s,$c,$cx,$cy,-$cx,-$cy));
      }
    }
    function _endpage()
    {
      if($this->angle!=0)
      {
        $this->angle=0;
        $this->_out('Q');
      }
      parent::_endpage();
    }
    function head($db){
      $this->SetFont('Arial','',10);
      $detail=$db->getSchool();
      foreach($detail as $key){
        $this->Image('assets/images/'.$key->Image,30,10,0,30);
        $this->SetFont('Courier','B','20');
        $this->Cell(300,20,$key->sName,0,0,'C');
        $this->Ln(15);
        $this->SetFont('Courier','B','10');
        $this->Cell(300,5,"Tel :".$key->Phone,0,0,'C');
        $this->Ln();
        $this->SetFont('Courier','B','10');
        $this->Cell(300,5,"P.O.Box ".$key->pBox." ".$key->pCode." ".$key->pCity." Kenya",0,0,'C');
        $this->Ln(10);
        $this->SetFont('Arial','IB','10');
        $this->Cell(320,5,"Approved Miscelaneous Amounts Statement as at ".date("D-Y-M-d"),0,0,'C');
				$this->Ln(10);
      }
    }
		function footer(){
			$this->SetY(-15);
			$this->SetFont('Arial','','10');
      $this->Cell(0,10,'=======================================================================================',0,0);
      $this->Ln(3);
			$this->Cell(0,10,'The School holds the right to edit the contents of this Document when necessary',0,0);
			$this->SetX(-40);
      $this->Ln();
      $this->SetTextColor(125,125,125);
			$this->Cell(0,0,'Generated By '.$_SESSION['role'],0,0);
		}
		function headerTable(){
			$this->SetFont('Arial','B','12');
			$this->Cell(20,5,'Amount',1,0,'C');
			$this->Cell(170,5,'Description',1,0,'C');
			$this->Cell(40,5,'Date Requested',1,0,'C');
			$this->Cell(40,5,'Date Approved',1,0,'C');
			$this->Ln();
		}
		function viewTable($db){
			$this->SetFont('Courier','I',10);
      $this->SetFillColor(10,90,100);
			$results=$db->displayApproved('maintenance');
      $total=0;
      foreach ($results as $data) {
        $this->SetTextColor(255,255,255);
				$this->Cell(20,5,$data->Amount,1,0,'C',true);
        $this->SetTextColor(0,0,0);
				$this->Cell(170,5,$data->Descr,1,0,'C');
        $this->SetTextColor(0,0,255);
				$this->Cell(40,5,$data->Dater,1,0,'C');
        $this->SetTextColor(255,0,0);
				$this->Cell(40,5,$data->DateA,1,0,'C');
        $this->SetTextColor(0,0,0);
        $this->Ln();
        $total=$total+$data->Amount;
			}
      	$this->Ln();
      $this->SetTextColor(255,0,0);
      $this->Cell(100,10,"Total Amount ",0,0,'C');
      $this->Cell(95,10,"===========",0,0,'R');
      $this->Ln(3);
      $this->Cell(100,10,"",0,0,'R');
      $this->Cell(95,10,"Ksh ".$total,0,0,'R');
      $this->Ln(3);
      $this->Cell(100,10," ",0,0,'R');
      $this->Cell(95,10,"===========",0,0,'R');
      $this->SetTextColor(0,0,0);
		}
	}
	$pdf=new myClass();
	$pdf->AliasNbPages();
	$pdf->AddPage('l','A4',0);
	$pdf->head($db);
	$pdf->headerTable();
	$pdf->viewTable($db);
	$pdf->output();
}else{  header("Location: index.php");}
?>
