<?php
session_start();
include('include/fpdf.php');
require_once('Database.php');
if(isset($_SESSION['role'])){
	include('head.php');
?>
	<body>
		<div id="app">
<?php
//perform access management
if($_SESSION['role']=="Administrator"){
	include('include/sidebar.php');
}

?>
			<div class="app-content">

						<?php include('include/header.php');?>

				<!-- end: TOP NAVBAR -->
				<div class="main-content" >
					<div class="wrap-content container" id="container">
            <?php
            $db=new Database();
            class myClass extends FPDF{
              // function head($db){
              //   $this->SetFont('Arial','',10);
              //   $statement=$db->query('select * from subject');
              //   if($data=$db->single(PDO::FETCH_OBJ)){
              //     //$this->Image('images/'.$data->image,10,10);
              //     $this->Image('assets/images/logo.png',10,10);
              //     $this->SetFont('Arial','B','10');
              //     $this->Cell(276,30,$data->subjectName.' Leave Applications',0,0,'C');
              //     $this->Cell(276,30,$data->subjectTitle,0,0,'C');
              //     $this->Ln(30);
              //   }
              //
              // }
              function footer(){
                $this->SetY(-15);
                $this->SetFont('Arial','','10');
                $this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0);
                $this->SetX(-40);
                $this->Cell(0,0,'Generated By '.$_SESSION['username'],0,0);
              }
              function headerTable(){
                $this->SetFont('Arial','B','12');
                $this->Cell(60,10,'Employee Number',1,0,'C');
                $this->Cell(30,10,'Return Date',1,0,'C');
                $this->Cell(80,10,'Reason',1,0,'C');
                $this->Cell(25,10,'Status',1,0,'C');
                $this->Ln();
              }
              // function viewTable($db){
              //   $this->SetFont('Arial','',10);
              //   $statement=$db->query('select * from users');
              //   while($data=$db->single(PDO::FETCH_OBJ)){
              //     $this->Cell(60,10,$data->id,1,0,'C');
              //     $this->Cell(30,10,$data->username,1,0,'C');
              //     // $this->Cell(80,10,$data->reason,1,0,'C');
              //     if($data->status==0){
              //       $status="Rejected";
              //     }else{
              //       $status="Approved";
              //     }
              //     $this->SetTextColor(255,0,0);
              //     $this->Cell(25,10,$status,1,0,'C');
              //     $this->Ln();
              //   }
              // }
            }
            $pdf=new myClass();
            $pdf->AliasNbPages();
            $pdf->AddPage('P','A4',0);
            // $pdf->head($db);
            $pdf->headerTable();
            $pdf->viewTable($db);
            $pdf->output();
             ?>
						<!-- start: PAGE TITLE -->
						<!-- end: PAGE TITLE -->
						<!-- start: BASIC EXAMPLE -->
					</div>
				</div>
			</div>
			<!-- start: FOOTER -->
	<?php include('include/footer.php');?>
		</div>
		<!-- start: MAIN JAVASCRIPTS -->
		<script src="vendor/jquery/jquery.min.js"></script>
		<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
		<script src="vendor/modernizr/modernizr.js"></script>
		<script src="vendor/jquery-cookie/jquery.cookie.js"></script>
		<script src="vendor/perfect-scrollbar/perfect-scrollbar.min.js"></script>
		<script src="vendor/switchery/switchery.min.js"></script>
		<script src="assets/js/main.js"></script>

		<script>
			jQuery(document).ready(function() {
				Main.init();
				FormElements.init();
			});
		</script>
		<!-- end: JavaScript Event Handlers for this page -->
		<!-- end: CLIP-TWO JAVASCRIPTS -->
	</body>
</html>
<?php }else{
	header("location: index.php");
}
