<?php
session_start();
if(isset($_SESSION['role'])){
  require_once('Database.php');
  $db=new Database();
	include('include/fpdf.php');
	class myClass extends FPDF{
    public $angle;
    public function Header(){
      $database=new Database();
      $details=$database->getSchool();
      foreach ($details as $key) {
        $this->SetFont('Arial','B','70');
        if($database->checkWatermark()){
          $this->watermark($key->sName,20,11);
        }else{
          continue;
        }
        $this->SetFont('Arial','B','10');
      }

    }
    function watermark($text,$angle,$start){
      $this->SetTextColor(255,200,233);
      $this->Rotate($angle,20,200);
      $this->Text($start,190,$text);
      $this->Rotate(0);
    }
    function Rotate($angle,$x=-1,$y=-1)
    {
      if($x==-1)
        $x=$this->x;
      if($y==-1)
        $y=$this->y;
      if($this->angle!=0)
        $this->_out('Q');
      $this->angle=$angle;
      if($angle!=0)
      {
        $angle*=M_PI/180;
        $c=cos($angle);
        $s=sin($angle);
        $cx=$x*$this->k;
        $cy=($this->h-$y)*$this->k;
        $this->_out(sprintf('q %.2F %.2F %.2F %.2F %.2F %.2F cm 1 0 0 1 %.2F %.2F cm',$c,$s,-$s,$c,$cx,$cy,-$cx,-$cy));
      }
    }
    function _endpage()
    {
      if($this->angle!=0)
      {
        $this->angle=0;
        $this->_out('Q');
      }
      parent::_endpage();
    }
    function head($db){
      $this->SetFont('Arial','',10);
      $detail=$db->getSchool();
      foreach($detail as $key){
        $this->Image('assets/images/'.$key->Image,30,10,0,40);
        $this->SetFont('Courier','B','20');
        $this->Cell(400,20,$key->sName,0,0,'C');
        $this->Ln(15);
        $this->SetFont('Courier','B','10');
        $this->Cell(400,5,"Tel :".$key->Phone,0,0,'C');
        $this->Ln();
        $this->SetFont('Courier','B','10');
        $this->Cell(400,5,"P.O.Box ".$key->pBox." ".$key->pCode." ".$key->pCity." Kenya",0,0,'C');
        $this->Ln(10);
        $this->SetFont('Arial','B','10');
        $this->Cell(400,5,"Students List as at ".date("D-Y-M-d"),0,0,'C');
        $this->Ln(30);
      }
    }
		function footer(){
			$this->SetY(-15);
			$this->SetFont('Arial','','10');
      $this->Cell(0,10,'=======================================================================================',0,0);
      $this->Ln(3);
			$this->Cell(0,10,'The School holds the right to edit the contents of this Document when necessary',0,0);
			$this->SetX(-40);
      $this->Ln();
      $this->SetTextColor(125,125,125);
			$this->Cell(0,0,'Generated By '.$_SESSION['role'],0,0);
		}
		function headerTable(){
			$this->SetFont('Arial','B','12');
			$this->Cell(80,10,'Names',1,0,'C');
			$this->Cell(50,10,'parent',1,0,'C');
			$this->Cell(20,10,'Class',1,0,'C');
			$this->Cell(80,10,'Stream',1,0,'C');
			$this->Cell(40,10,'Reg. Number',1,0,'C');
			$this->Cell(20,10,'Gender',1,0,'C');
			$this->Cell(50,10,'Dormitory',1,0,'C');
			$this->Cell(40,10,'Status',1,0,'C');
			$this->Ln();
		}
		function viewTable($db){
			$this->SetFont('Arial','',10);
			$results=$db->displayTable('student');
      $total=0;
      foreach ($results as $data) {
        if($data->class <1){
          continue;
        }
				$this->Cell(80,10,$data->names,1,0,'C');
				$this->Cell(50,10,$data->parent,1,0,'C');
				$this->Cell(20,10,$data->class,1,0,'C');
				$this->Cell(80,10,$data->stream,1,0,'C');
				$this->Cell(40,10,$data->regNo,1,0,'C');
				$this->Cell(20,10,$data->gender,1,0,'C');
				$this->Cell(50,10,$data->dorm,1,0,'C');
				if($data->status==1){
          $this->SetTextColor(0,255,0);
          $this->Cell(40,10,"Present",1,0,'C');
          $this->SetTextColor(0,0,0);
        }else{
          $this->SetTextColor(255,0,0);
          $this->Cell(40,10,"Suspended/Transferred",1,0,'C');
          $this->SetTextColor(0,0,0);
        }
        $this->Ln();
        $total=$total+1;
			}
      	$this->Ln();
      $this->SetTextColor(0,0,0);
      $this->Cell(250,10,"Total ",0,0,'C');
      $this->Cell(95,10,"===========",0,0,'C');
      $this->Ln(3);
      $this->Cell(250,10,"",0,0,'C');
      $this->Cell(95,10,$total." Students",0,0,'C');
      $this->Ln(3);
      $this->Cell(250,10," ",0,0,'C');
      $this->Cell(95,10,"===========",0,0,'C');
		}
	}
	$pdf=new myClass();
	$pdf->AliasNbPages();
	$pdf->AddPage('l','A3',0);
	$pdf->head($db);
	$pdf->headerTable();
	$pdf->viewTable($db);
	$pdf->output();
}else{  header("Location: index.php");}
?>
