<?php
session_start();
if(isset($_SESSION['username'])){
  require_once('Database.php');
  $db=new Database();
	include('include/fpdf.php');
	class myClass extends FPDF{
		function head($db){
			$this->SetFont('Arial','IB',10);
			$db->query('select * from users');
      $statement=$db->resultSet();
			foreach ($statement as $data){
				// $this->Image('images/'.$data->image,10,10);
				$this->SetFont('Arial','B','10');
				$this->Cell(200,20,$data->companyName,0,0,'C');
				$this->Ln(5);
				$this->Cell(200,30,$data->contact,0,0,'C');
				$this->Ln(5);
				$this->Cell(200,30,'Salary PaySlips',0,0,'C');
				$this->Ln(10);
				$this->SetFont('Courier','IB',9);
			}

		}
		function footer(){
			$this->SetY(-15);
			$this->SetFont('Arial','','10');
			// $this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0);
			$this->SetX(-40);
			$this->Cell(0,0,'Generated By '.$_SESSION['username'],0,0);
		}
		function viewTable($db){
			$db->query('select * from payments');
      $stat=$db->resultSet();
			foreach($stat as $key){
				$this->Cell(0,0,$this->head($db),0,0,'C');
				$this->Ln(2);
				$this->SetTextColor(0,0,0);
				$this->Cell(50,10,'Employee Name :'.$data->fname.' '.$data->sname);
				$this->Ln(5);
				$this->Cell(50,10,'Designation :'.$data->level);
				$this->Ln(5);
				$this->Cell(50,10,'Employee Number: '.$data->empNumber);
				$this->Ln(5);
				$this->Cell(50,10,'ID. Number: '.$data->id_number);
				$this->Ln(5);
				$date=date("Y-M-d");
				$this->Cell(40,10,'Generated:'.$date,0,0,'C');
				$this->Ln(8);
				$this->Cell(50,10,'Earnings',1,0,'C');
				$this->Cell(45,10,'',1,0,'C');
				$this->Cell(50,10,'Deductions',1,0,'C');
				$this->Cell(45,10,'',1,0,'C');
				$this->Ln(10);
				$this->Cell(50,10,'Salary',1,0,'C');
				$this->Cell(45,10,$data->salary,1,0,'C');
				$this->Cell(50,10,'Loan Repayment',1,0,'C');
				$this->Cell(45,10,"sam",1,0,'C');
				$this->Ln(10);
				$this->Cell(50,10,'Allowances',1,0,'C');
				$this->Cell(45,10,"djhdjh",1,0,'C');
				$this->Cell(50,10,'Deductions',1,0,'C');
				$this->Cell(45,10,"dhhd",1,0,'C');
				$this->Ln(10);
				$this->Cell(50,10,'Overtime',1,0,'C');
				$this->Cell(45,10,"dgdg",1,0,'C');
				$this->Cell(50,10,'Loan Balance',1,0,'C');
				$this->Cell(45,10,"dgdg",1,0,'C');
				$this->Ln(10);
				$this->Cell(50,5,'Gross pay',1,0,'C');
				$gPay=4000;
				$this->Cell(45,5,$gPay,1,0,'C');
				$this->Cell(50,5,'Total',1,0,'C');
				$tDeductions=5000;
				$this->Cell(45,5,'Ksh '.$tDeductions,1,0,'C');
				$this->Ln();
				$this->SetTextColor(255,0,0);
				$this->Cell(50,5,'Net Salary',1,0,'C');
				$netPay=5000;
				$this->Cell(45,5,'Ksh '.$netPay,1,0,'C');
				$this->Ln();
				$this->SetTextColor(0,0,0);
				//$this->pay($db,$data->empNumber,$gPay,$this->getDeductions($db,$data->empNumber),$this->getBalance($db,$data->empNumber),$this->getAllowance($db),$this->getOvertime($db,$data->empNumber),$netPay);

			}
		}
	}
	$pdf=new myClass();
	$pdf->AddPage('L','A5',0);
	$pdf->viewTable($db);
	$pdf->output();
}else{  header("Location: index.php");}
?>
