<?php
session_start();
if(isset($_SESSION['role'])){
  $_SESSION['class']=$_GET['Class'];
  $_SESSION['term']=$_GET['Term'];
  $_SESSION['year']=$_GET['Year'];
  $_SESSION['exam']=$_GET['Num'];
  require_once('Database.php');
  $db=new Database();
	include('include/fpdf.php');
	class myClass extends FPDF{
    public $angle;
    public function Header(){
      $database=new Database();
      $details=$database->getSchool();
      foreach ($details as $key) {
        $this->SetFont('Arial','B','70');
        if($database->checkWatermark()){
          $this->watermark($key->sName,30,11);
        }else{
          continue;
        }
        $this->SetFont('Arial','B','10');
      }

    }
    function watermark($text,$angle,$start){
      $this->SetTextColor(255,200,233);
      $this->Rotate($angle,20,200);
      $this->Text($start,190,$text);
      $this->Rotate(0);
    }
    function Rotate($angle,$x=-1,$y=-1)
    {
      if($x==-1)
        $x=$this->x;
      if($y==-1)
        $y=$this->y;
      if($this->angle!=0)
        $this->_out('Q');
      $this->angle=$angle;
      if($angle!=0)
      {
        $angle*=M_PI/180;
        $c=cos($angle);
        $s=sin($angle);
        $cx=$x*$this->k;
        $cy=($this->h-$y)*$this->k;
        $this->_out(sprintf('q %.2F %.2F %.2F %.2F %.2F %.2F cm 1 0 0 1 %.2F %.2F cm',$c,$s,-$s,$c,$cx,$cy,-$cx,-$cy));
      }
    }
    function _endpage()
    {
      if($this->angle!=0)
      {
        $this->angle=0;
        $this->_out('Q');
      }
      parent::_endpage();
    }
		function head($db,$class,$stream){
			$this->SetFont('Arial','',10);
      $this->SetFont('Arial','',10);
      $detail=$db->getSchool();
      foreach($detail as $key){
				$this->Image('assets/images/'.$key->Image,40,10,0,25);
				$this->SetFont('Courier','B','20');
				$this->Cell(275,20,$key->sName,0,0,'C');
        $this->Ln(15);
        $this->SetFont('Courier','B','10');
				$this->Cell(275,5,"Tel :".$key->Phone,0,0,'C');
        $this->Ln();
        $this->SetFont('Courier','B','10');
				$this->Cell(275,5,"P.O.Box ".$key->pBox." ".$key->pCode." ".$key->pCity." Kenya",0,0,'C');
				$this->Ln(5);
        $this->SetFont('Arial','B','10');
				$this->Cell(275,5,"Form ".$class." Class",0,0,'C');
				$this->Ln(5);
        $this->Cell(275,5,$_SESSION['exam']." Subjects Analysis Report",0,0,'C');
        $this->Ln(10);
      }
		}
		function footer(){
			$this->SetY(-15);
			$this->SetFont('Arial','','10');
      $this->Cell(0,10,'=======================================================================================',0,0);
      $this->Ln(3);
			$this->Cell(0,10,'The School holds the right to edit the contents of this Document when necessary',0,0);
			$this->SetX(-40);
      $this->Ln();
      $this->SetTextColor(125,125,125);
			$this->Cell(0,0,'Generated By '.$_SESSION['role'],0,0);
		}
		function headerTable(){
      $this->SetLeftMargin(30);
			$this->SetFont('courier','IB',8);
			$this->Cell(16,5,'S/N',1,0,'C');
			$this->Cell(20,5,'Stream',1,0,'C');
			$this->Cell(10,5,'A',1,0,'C');
			$this->Cell(10,5,'A-',1,0,'C');
			$this->Cell(10,5,'B+',1,0,'C');
			$this->Cell(10,5,'B',1,0,'C');
			$this->Cell(10,5,'B-',1,0,'C');
			$this->Cell(10,5,'C+',1,0,'C');
			$this->Cell(10,5,'C',1,0,'C');
			$this->Cell(10,5,'C-',1,0,'C');
			$this->Cell(10,5,'D+',1,0,'C');
			$this->Cell(10,5,'D',1,0,'C');
			$this->Cell(10,5,'D-',1,0,'C');
			$this->Cell(10,5,'E',1,0,'C');
			$this->Cell(10,5,'X',1,0,'C');
			$this->Cell(20,5,'Entry',1,0,'C');
			$this->Cell(20,5,'PINDEX',1,0,'C');
			$this->Cell(20,5,'Mean Grade',1,0,'C');
			$this->Ln();
		}
		function viewTable($db){
      $subjects=$db->displayApproved('subject');
      foreach ($subjects as $subject) {
        	$this->SetFont('Arial','IB',8);
          $this->SetLeftMargin(40);
        $this->Cell(200,10,$subject->subjectName,0,0,'C');
        $this->Ln(13);
        $this->headerTable();
        $this->SetLeftMargin(40);
        $streams=$db->displayApproved('stream');
        $pos=1;
        foreach ($streams as $stream) {
          $streamTotals=$db->getStreamTotals($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],$stream->streamName);
          $gA=$db->getGradeCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"A",$stream->streamName);
          $AMin=$db->getGradeCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"A-",$stream->streamName);
          $BP=$db->getGradeCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"B+",$stream->streamName);
          $B=$db->getGradeCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"B",$stream->streamName);
          $BMin=$db->getGradeCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"B-",$stream->streamName);
          $CP=$db->getGradeCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"C+",$stream->streamName);
          $C=$db->getGradeCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"C",$stream->streamName);
          $CM=$db->getGradeCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"C-",$stream->streamName);
          $DP=$db->getGradeCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"D+",$stream->streamName);
          $D=$db->getGradeCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"D",$stream->streamName);
          $DM=$db->getGradeCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"D-",$stream->streamName);
          $E=$db->getGradeCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"E",$stream->streamName);
          $X=$db->getGradeCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"-",$stream->streamName);
          $this->Cell(16,5,$pos,1,0,'C');
          $this->Cell(20,5,$stream->streamName,1,0,'C');
          $this->Cell(10,5,$gA,1,0,'C');
          $this->Cell(10,5,$AMin,1,0,'C');
          $this->Cell(10,5,$BP,1,0,'C');
          $this->Cell(10,5,$B,1,0,'C');
          $this->Cell(10,5,$BMin,1,0,'C');
          $this->Cell(10,5,$CP,1,0,'C');
          $this->Cell(10,5,$C,1,0,'C');
          $this->Cell(10,5,$CM,1,0,'C');
          $this->Cell(10,5,$DP,1,0,'C');
          $this->Cell(10,5,$D,1,0,'C');
          $this->Cell(10,5,$DM,1,0,'C');
          $this->Cell(10,5,$E,1,0,'C');
          $this->Cell(10,5,$X,1,0,'C');
          $entry=$gA+$AMin+$BP+$B+$BMin+$CP+$C+$CM+$DP+$D+$DM+$E+$X;
          $this->Cell(20,5,$entry,1,0,'C');
          if($entry==0){
            $pi=0;
          }else{
            $pi=$streamTotals/$entry;
          }
          $mean=$pi;
          $this->Cell(20,5,number_format($mean,4),1,0,'C');
          if(round($mean)==12){
            $g="A";
          }
          elseif (round($mean)==11) {
            $g='A-';
          }
          elseif (round($mean)==10) {
            $g='B+';
          }
          elseif(round($mean)==9){
            $g='B';
          }elseif(round($mean)==8){
            $g='B-';
          }elseif (round($mean)==7) {
            $g='C+';
          }elseif(round($mean)==6){
            $g='C';
          }elseif (round($mean)==5) {
            $g='C-';
          }elseif(round($mean)==4){
            $g='D+';
          }elseif (round($mean)==3) {
            $g='D';
          }elseif (round($mean)==2) {
            $g='D-';
          }elseif (round($mean)==1) {
            $g='E';
          }else{
            $g='-';
        }
          $this->Cell(20,5,$g,1,0,'C');
          $this->Ln();
          $pos=$pos+1;
        }
        $classTotals=$db->getClassTotals($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year']);
        $gA=$db->getOverallCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"A");
        $AMin=$db->getOverallCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"A-");
        $BP=$db->getOverallCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"B+");
        $B=$db->getOverallCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"B");
        $BMin=$db->getOverallCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"B-");
        $CP=$db->getOverallCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"C+");
        $C=$db->getOverallCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"C");
        $CM=$db->getOverallCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"C-");
        $DP=$db->getOverallCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"D+");
        $D=$db->getOverallCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"D");
        $DM=$db->getOverallCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"D-");
        $E=$db->getOverallCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"E");
        $X=$db->getOverallCount($subject->subjectName,$_SESSION['class'],$_SESSION['exam'],$_SESSION['term'],$_SESSION['year'],"-");
        $this->Cell(16,5,'',1,0,'C');
        $this->Cell(20,5,'Overall',1,0,'C');
        $this->Cell(10,5,$gA,1,0,'C');
        $this->Cell(10,5,$AMin,1,0,'C');
        $this->Cell(10,5,$BP,1,0,'C');
        $this->Cell(10,5,$B,1,0,'C');
        $this->Cell(10,5,$BMin,1,0,'C');
        $this->Cell(10,5,$CP,1,0,'C');
        $this->Cell(10,5,$C,1,0,'C');
        $this->Cell(10,5,$CM,1,0,'C');
        $this->Cell(10,5,$DP,1,0,'C');
        $this->Cell(10,5,$D,1,0,'C');
        $this->Cell(10,5,$DM,1,0,'C');
        $this->Cell(10,5,$E,1,0,'C');
        $this->Cell(10,5,$X,1,0,'C');
        $entry=$gA+$AMin+$BP+$B+$BMin+$CP+$C+$CM+$DP+$D+$DM+$E+$X;
        $this->Cell(20,5,$entry,1,0,'C');
        if($entry==0){
          $pi=0;
        }else{
          $pi=$classTotals/$entry;
        }
        $mean=number_format($pi,4);
        $this->Cell(20,5,$mean,1,0,'C');
        if(round($mean)==12){
          $g="A";
        }
        elseif (round($mean)==11) {
          $g='A-';
        }
        elseif (round($mean)==10) {
          $g='B+';
        }
        elseif(round($mean)==9){
          $g='B';
        }elseif(round($mean)==8){
          $g='B-';
        }elseif (round($mean)==7) {
          $g='C+';
        }elseif(round($mean)==6){
          $g='C';
        }elseif (round($mean)==5) {
          $g='C-';
        }elseif(round($mean)==4){
          $g='D+';
        }elseif (round($mean)==3) {
          $g='D';
        }elseif (round($mean)==2) {
          $g='D-';
        }elseif (round($mean)==1) {
          $g='E';
        }else{
          $g='-';
      }
        $this->Cell(20,5,$g,1,0,'C');
        $this->Ln();
      }
	}
}
	$pdf=new myClass();
	$pdf->AliasNbPages();
	  $pdf->AddPage('p','A3',0);
	$pdf->head($db,$_SESSION['class'],$_SESSION['stream']);
	//$pdf->headerTable();
	$pdf->viewTable($db);
	$pdf->output();
}else{  header("Location: index.php");}
?>
