<?php
session_start();
if(isset($_SESSION['role'])){
  $_SESSION['student']=$_POST['student'];
  require_once('Database.php');
  $db=new Database();
	include('include/fpdf.php');
	class myClass extends FPDF{
    public $angle;
    public function Header(){
      $database=new Database();
      $details=$database->getSchool();
      foreach ($details as $key) {
        $this->SetFont('Arial','B','70');
        if($database->checkWatermark()){
          $this->watermark($key->sName,30,11);
        }else{
          continue;
        }
        $this->SetFont('Arial','B','10');
      }

    }
    function watermark($text,$angle,$start){
      $this->SetTextColor(255,200,233);
      $this->Rotate($angle,20,200);
      $this->Text($start,190,$text);
      $this->Rotate(0);
    }
    function Rotate($angle,$x=-1,$y=-1)
    {
      if($x==-1)
        $x=$this->x;
      if($y==-1)
        $y=$this->y;
      if($this->angle!=0)
        $this->_out('Q');
      $this->angle=$angle;
      if($angle!=0)
      {
        $angle*=M_PI/180;
        $c=cos($angle);
        $s=sin($angle);
        $cx=$x*$this->k;
        $cy=($this->h-$y)*$this->k;
        $this->_out(sprintf('q %.2F %.2F %.2F %.2F %.2F %.2F cm 1 0 0 1 %.2F %.2F cm',$c,$s,-$s,$c,$cx,$cy,-$cx,-$cy));
      }
    }
    function _endpage()
    {
      if($this->angle!=0)
      {
        $this->angle=0;
        $this->_out('Q');
      }
      parent::_endpage();
    }
		function head($db,$class,$stream){
			$this->SetFont('Arial','',10);
      $this->SetFont('Arial','',10);
      $detail=$db->getSchool();
      foreach($detail as $key){
				$this->Image('assets/images/'.$key->Image,40,10,0,25);
				$this->SetFont('Courier','B','20');
				$this->Cell(275,20,$key->sName,0,0,'C');
        $this->Ln(15);
        $this->SetFont('Courier','B','10');
				$this->Cell(275,5,"Tel :".$key->Phone,0,0,'C');
        $this->Ln();
        $this->SetFont('Courier','B','10');
				$this->Cell(275,5,"P.O.Box ".$key->pBox." ".$key->pCode." ".$key->pCity." Kenya",0,0,'C');
                $this->Ln(5);
                $db=new Database();
                $sname=$db->getName($_SESSION['student']);
        $this->Cell(275,5,$sname." Progress Records",0,0,'C');
        $this->Ln(10);
      }
		}
		function footer(){
			$this->SetY(-15);
			$this->SetFont('Arial','','10');
      $this->Cell(0,10,'=======================================================================================',0,0);
      $this->Ln(3);
			$this->Cell(0,10,'The School holds the right to edit the contents of this Document when necessary',0,0);
			$this->SetX(-40);
      $this->Ln();
      $this->SetTextColor(125,125,125);
			$this->Cell(0,0,'Generated By '.$_SESSION['role'],0,0);
		}
		function headerTable(){
      $this->SetLeftMargin(30);
			$this->SetFont('Arial','',12);
			$this->Cell(25,5,'Exam',1,0,'C');
            $this->Cell(30,5,'Total Marks',1,0,'C');
            $this->Cell(30,5,'Total Points',1,0,'C');
			$this->Cell(20,5,'Class',1,0,'C');
			$this->Cell(20,5,'Stream',1,0,'C');
			$this->Cell(20,5,'Term',1,0,'C');
			$this->Cell(20,5,'Year',1,0,'C');
			$this->Cell(20,5,'Position',1,0,'C');
			$this->Cell(32,5,'Stream Position',1,0,'C');
			$this->Cell(20,5,'Grade',1,0,'C');
			$this->Ln();
		}
		function viewTable($db){
      $subjects=$db->displayApproved('classes');
      foreach ($subjects as $subject) {
        $this->SetFont('Arial','IB',8);
        $this->SetLeftMargin(40);
        $this->Cell(200,10,"Form ".$subject->form,0,0,'C');
        $this->Ln(13);
        $this->headerTable();
        $this->SetLeftMargin(40);
        $db->query('SELECT * FROM  examTotals WHERE Class=:class AND studentReg=:studentReg');
        $db->bind(':class',$subject->form);
        $db->bind(':studentReg',$_SESSION['student']);
        $progress=$db->resultSet();
        foreach($progress as $pg){
            $this->SetFont('Arial','',12);
			$this->Cell(25,5,$pg->exam,1,0,'C');
            $this->Cell(30,5,$pg->total,1,0,'C');
            $this->Cell(30,5,$pg->points,1,0,'C');
			$this->Cell(20,5,$pg->Class,1,0,'C');
			$this->Cell(20,5,$pg->Stream,1,0,'C');
			$this->Cell(20,5,$pg->term,1,0,'C');
			$this->Cell(20,5,$pg->year,1,0,'C');
			$this->Cell(20,5,$pg->position,1,0,'C');
			$this->Cell(32,5,$pg->StreamPosition,1,0,'C');
			$this->Cell(20,5,$pg->Grade,1,0,'C');
			$this->Ln();
        }
    }
	}
}
	$pdf=new myClass();
	$pdf->AliasNbPages();
	$pdf->AddPage('p','A3',0);
	$pdf->head($db,$_SESSION['class'],$_SESSION['stream']);
	//$pdf->headerTable();
	$pdf->viewTable($db);
	$pdf->output();
}else{  header("Location: index.php");}
?>
